### ISSUE TITLE
Javascript mimarisinin belirlenmesi 

### ISSUE THREAD

**Issue by d46** [gricreative/gri-cengo-kit#10]
Javascript tarafinda mimari bir kac yapi ornegi belirlememiz gerekiyor.

**Comment by toneyavuz** [comment]
$(function(){
function Person(first, last, age, eyecolor) {
    this.firstName = first;
    this.lastName = last;
    this.age = age;
    this.eyeColor = eyecolor;
}
Person.prototype.nationality = "English";

var newPerson = new Person('kutbettin', 'yavuz', 23, 'blue');
newPerson.nationality = 'Turkish';

console.log(newPerson);
});

bu bir yapidir. belki yani, olabilir sanki, denemek yada arge etmek lazım.

**Comment by d46** [comment]
Bu bir builder pattern. http://www.dofactory.com/javascript/builder-design-pattern

Kullanacagimiz yerler buyuk ihtimal olur.

**Comment by d46** [comment]
v0.1 ile genel bir mimari cikartildi.
