### ISSUE TITLE
Magic CSS Animate

### ISSUE THREAD

**Issue by toneyavuz** [gricreative/gri-cengo-kit#13]
effectleri çok hoştır, projelerde bower kullanacaksak bunu da kullanabiliriz. Ne dersiniz.

http://www.minimamente.com/example/magic_animations/

**Comment by d46** [comment]
fikir guzel ama efektleri begenemedim.kullanisiz geldi :(

**Comment by toneyavuz** [comment]
uygulama yazılacaksa yerine göre güzel tabi uygulama burada biraz zor yazılır.
https://daneden.github.io/animate.css/
Buda her yerde kullanılabilecek cinsten. Büyük ihtimalle biliyorsunuzdur.

**Comment by d46** [comment]
+1 Bence olur. Ama bu diger sass frameworkunde var mi hepsi.
