### ISSUE TITLE
Menu iconlari

### ISSUE THREAD

**Issue by d46** [gricreative/gri-cengo-kit#14]
Menu iconlari icin soyle bir plugin kullanabiliriz. 

http://tympanus.net/Tutorials/AnimatedMenuIcon/

yada buradaki gibi

http://tympanus.net/Tutorials/MotionBlurEffect/menu.html

**Comment by toneyavuz** [comment]
Codepen'de de baya var, bunlara da bakabilir siniz.
http://codepen.io/search/pens/?depth=everything&limit=all&order=popularity&page=2&q=menu+icon&show_forks=false

https://codepen.io/designcouch/pen/Atyop
http://codepen.io/pedrocampos/pen/gufrx
http://codepen.io/michaeltcoelho/pen/awGzf
